### ISSUE TITLE
Q - CSV Option

### ISSUE THREAD

**Issue by dneto82** [twaddington/python-rdio-export#1]
Hi mate, how Can I extract in CSV format. 

You script is amazing, I'm trying to use with Ivy (http://www.ivyishere.org/ivy) to migrate from Rdio to Spotify. 

This website only accept CSV, iTunes XML or Artist + Titles.

Can you help me?

Ps.: Do you accept paypal donations?

**Comment by twaddington** [comment]
Hey, sorry for the delayed replay, GitHub was apparently not sending me notifications on this repository.

The script doesn't currently support exporting to a CSV file but I'll consider it in the future. It should be easy to modify it to do so.

**Comment by twaddington** [comment]
This was added.
