### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by purplehat7** [twaddington/python-rdio-export#2]
Useful stuff, just a few suggestions for additions/modifications to your README:
1. I didn't need to perform the publishing steps to get everything to work correctly...
2. You should explain in the docs that the user's collection is printed to stdout, so users will know to redirect it to a file accordingly, e.g. `rdio-export --email <email> > output.md`
3. You should also explain how to set the proper Rdio env vars (e.g. `RDIO_CONSUMER_KEY` and `RDIO_CONSUMER_SECRET`).

**Comment by twaddington** [comment]
Hey, sorry for the delayed replay, GitHub was apparently not sending me notifications on this repository.

> I didn't need to perform the publishing steps to get everything to work correctly...

Thanks for the feedback, the publishing steps are just internal notes for myself. I'll move them out of the README and into a RELEASING file like I have in my other repositories.

> You should explain in the docs that the user's collection is printed to stdout, so users will know to redirect it to a file accordingly, e.g. rdio-export --email <email> > output.md

Will do, apparently that's not obvious.

> You should also explain how to set the proper Rdio env vars (e.g. RDIO_CONSUMER_KEY and RDIO_CONSUMER_SECRET).

This should be pretty obvious for folks who're familiar with env variables but I'll try to update the documentation to be more clear about the various options.

**Comment by twaddington** [comment]
Okay, I fixed up the README. Let me know if it makes more sense now!

**Comment by purplehat7** [comment]
Yup thanks!
