### ISSUE TITLE
File bin/rdio-export is missing from git

### ISSUE THREAD

**Issue by WhyNotHugo** [twaddington/python-rdio-export#3]
The file `bin/rdio-export`, referenced in setup.py is missing from git.

```
$ python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/rdio_export
copying rdio_export/exporter.py -> build/lib/rdio_export
copying rdio_export/__init__.py -> build/lib/rdio_export
running build_scripts
creating build/scripts-3.4
error: file '/home/hugo/tmp/python-rdio-export/bin/rdio-export' does not exist
```

**Comment by twaddington** [comment]
Hey, sorry for the delayed replay, GitHub was apparently not sending me notifications on this repository.

> The file bin/rdio-export, referenced in setup.py is missing from git.

I'm not sure why you're seeing that error. Have you tried `$ python setup.py develop` or `$ python setup.py install` instead? The file is located here:

https://github.com/twaddington/python-rdio-export/blob/master/bin/rdio-export

**Comment by twaddington** [comment]
Let me know if this is still an issue for you.

**Comment by WhyNotHugo** [comment]
No, I can no longer reproduce the issue. I've no idea what the original problem was.

Thanks.
